name: 'sage_intacct_source'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  sage_intacct_source:
    +schema: sage_intacct_staging
    materialized: table
    tmp:
      materialized: view

vars:
  sage_intacct_source:
    gl_detail:                    "{{ source('sage_intacct','gl_detail') }}"
    gl_account:                   "{{ source('sage_intacct','gl_account') }}"
    ap_bill_item:                 "{{ source('sage_intacct','ap_bill_item') }}"
    ap_bill:                      "{{ source('sage_intacct','ap_bill') }}"
    ar_invoice_item:              "{{ source('sage_intacct','ar_invoice_item') }}"
    ar_invoice:                   "{{ source('sage_intacct','ar_invoice') }}"
    
    account_pass_through_columns: []
    gl_pass_through_columns: []
    
clean-targets:
    - target
    - dbt_modules
